#spring:
#  jpa:
#    database: mysql
#    generate-ddl: false
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        show_sql: true
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy